---
- name: "Enable and start InfluxDB"
  register: install_influxdb__service_status
  failed_when: not (install_influxdb__service_status.state != "started" or install_influxdb__service_status.state != "inactive")
  changed_when: not (install_influxdb__service_status.state != "started" or install_influxdb__service_status.state != "inactive")
  ansible.builtin.service:
    name: "influxdb"
    state: "started"
    enabled: yes
    daemon_reload: true

- name: "Restart InfluxDB"
  register: install_influxdb__service_status
  failed_when: not install_influxdb__service_status.state != "restarted"
  changed_when: not install_influxdb__service_status.state != "restarted"
  ansible.builtin.service:
    name: "influxdb"
    state: "restarted"
    daemon_reload: true
