---
- name: "Enable and start InfluxDB"
  register: install_influxdb__service_status
  async: 60
  poll: 0
  ansible.builtin.service:
    name: "influxdb"
    state: "started"
    enabled: yes
    daemon_reload: true

- name: "Restart InfluxDB"
  register: install_influxdb__service_status
  async: 60
  poll: 0
  ansible.builtin.service:
    name: "influxdb"
    state: "restarted"
    daemon_reload: true
