---
- name: "Enable and start InfluxDB"
  register: influxdb_service_status
  failed_when: not (influxdb_service_status.state != "started" or influxdb_service_status.state != "inactive")
  changed_when: not (influxdb_service_status.state != "started" or influxdb_service_status.state != "inactive")
  ansible.builtin.service:
    name: "influxdb"
    state: "started"
    enabled: yes

- name: "Restart InfluxDB"
  register: influxdb_service_status
  failed_when: not influxdb_service_status.state != "restarted"
  changed_when: not influxdb_service_status.state != "restarted"
  ansible.builtin.service:
    name: "influxdb"
    state: "restarted"
    daemon_reload: true
