---
- name: "Converge"
  hosts: "local"
  tasks:

    - name: "Include labocbz.install_influxdb"
      tags:
        - "labocbz.install_influxdb"
      vars:
        install_influxdb__http_bind_address: "{{ inv_install_influxdb__http_bind_address }}"
        install_influxdb__http_bind_port: "{{ inv_install_influxdb__http_bind_port }}"
        install_influxdb__ssl: "{{ inv_install_influxdb__ssl }}"
        install_influxdb__ssl_domain: "{{ inv_install_influxdb__ssl_domain }}"
        install_influxdb__ssl_key: "{{ inv_install_influxdb__ssl_key }}"
        install_influxdb__ssl_cert: "{{ inv_install_influxdb__ssl_cert }}"
      ansible.builtin.include_role:
        name: "labocbz.install_influxdb"
