---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "cicd-ubuntu-22"
  gather_facts: false
  tasks:

    - name: "Get InfluxDB service current state"
      register: install_influxdb__service_status
      failed_when: not install_influxdb__service_status.status.ActiveState == 'active'
      ansible.builtin.systemd:
        name: "influxdb"

    - name: "Check InfluxDB env file"
      register: folder_check
      failed_when: not folder_check.stat.exists
      ansible.builtin.stat:
        path: "/etc/default/influxdb2"

    - name: "Check InfluxDB connectivity"
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ inv_install_influxdb__http_bind_port }}"
        timeout: 120

    - name: "Check SSL/TLS access"
      when: inv_install_influxdb__ssl
      register: result
      failed_when: result.status != 200
      ansible.builtin.uri:
        url: "https://{{ inventory_hostname }}:{{ inv_install_influxdb__http_bind_port }}/"
        method: "GET"
        validate_certs: true
